vanotsintsabadze1/Distribo

app/dashboard/company/page.tsx, app/dashboard/layout.tsx, app/dashboard/page.tsx, app/dashboard/user/page.tsx, components/dashboard/Header.tsx, components/dashboard/Logo.tsx, components/dashboard/Navigation.tsx, components/dashboard/SideBar.tsx, tailwind.config.ts
Added:
- Responsive and user-friendly administrator dashboard.
=> Add administrator dashboard

app/auth/login/page.tsx, app/auth/signup/page.tsx, app/globals.css, components/UI/Button.tsx, components/auth/LoginForm.tsx, components/auth/SignupForm.tsx
Fixes:
- Fixed the issue with dynamic classes not being applied when constructing a new component by using conditionals & inline style props for the button element.
Follow up docs:
- [https://tailwindcss.com/docs/content-configuration#dynamic-class-names](url)
=> Fix dynamic class issues with tailwind for custom button component

components/UI/TextArea.tsx, components/UI/TextInput.tsx, components/auth/LoginForm.tsx, components/auth/SignupForm.tsx, components/company/CompanyCreationButton.tsx, components/company/creation/CompanyCreationForm.tsx, lib/schema/schema.ts, lib/utils/validation.ts, types/schema-types.ts
Implement controlled input fields for the login, signup, and create-company forms. Set up Zod schemas to handle form validation for each of these forms, ensuring that all input data is validated according to the defined schema before submission.
=> Add forms validation

.prettierrc, app/dashboard/company/page.tsx, app/dashboard/user/page.tsx, app/dashboard/users/create/page.tsx, app/dashboard/users/page.tsx, components/UI/Button.tsx, components/UI/ErrorMessage.tsx, components/UI/TextInput.tsx, components/auth/LoginForm.tsx, components/auth/SignupForm.tsx, components/company/CompanyCreationButton.tsx, components/company/creation/CompanyCreationForm.tsx, components/dashboard/Navigation.tsx, components/users/UserCreationForm.tsx, components/users/UserCreationNavigatorButton.tsx, lib/schema/schema.ts, lib/utils/validation.ts, types/schema-types.ts
Added:
- Implemented user creation form with it's own error handling.
- Implemented error message component that renders error if need be.
=> Implement user creation form & error handling component

app/dashboard/page.tsx, components/auth/login/LoginForm.tsx, components/users/UserCreationForm.tsx, lib/actions/admin/users/createUser.tsx, lib/actions/auth/auth.ts, lib/utils/apiResponseValidator.ts, types/types.d.ts
Added:
- General function that handles and displays either a success or an error toast depending on the status code.
=> Create an API response handler to ease the response management

app/dashboard/page.tsx, app/dashboard/products/create/page.tsx, app/dashboard/products/page.tsx, app/dashboard/users/page.tsx, components/UI/ErrorMessage.tsx, components/UI/TextArea.tsx, components/UI/TextInput.tsx, components/dashboard/Navigation.tsx, components/products/ProductCreationForm.tsx, components/products/ProductCreationNavigatorButton.tsx, components/users/UserCreationForm.tsx, lib/schema/schema.ts, types/schema-types.ts
Add:
- create product and product create pages
- product creation form
=> Add product create form

app/dashboard/company/page.tsx, app/dashboard/products/page.tsx, app/dashboard/profile/page.tsx, app/dashboard/users/page.tsx, components/UI/PageLayoutComp.tsx, components/UI/TextInput.tsx, components/company/CompanyCreationNavigatorButton.tsx, components/dashboard/Navigation.tsx, components/products/ProductCreationNavigatorButton.tsx, components/profile/Profile.tsx, components/users/UserCreationNavigatorButton.tsx
Add
- create user profile page
- display user information
- create reusable page layout component
=> Add user profile page

app/dashboard/page.tsx, app/dashboard/products/page.tsx, app/globals.css, components/products/ProductCard.tsx, components/products/ProductCreationForm.tsx, components/products/ProductsWrapper.tsx, lib/utils/fetchImages.ts, package.json, types/types.d.ts
Added:
- Created a wrapper to showcase all the products.
- Helper function to retrieve a single image for a cover or all the images, transform them to blob URLs and retrieve them as files.
=> Add products wrapper & products fetching functionality

app/dashboard/products/edit/[id]/page.tsx, app/dashboard/products/edit/page.tsx, app/dashboard/products/page.tsx, components/UI/PageLayoutComp.tsx, components/dashboard/SideBar.tsx, components/products/ProductActionsBar.tsx, components/products/ProductCard.tsx, components/products/ProductEditForm.tsx, components/products/ProductsWrapper.tsx, lib/actions/admin/products/editProduct.ts, lib/utils/fetchImages.ts, next.config.mjs
Added:
- Functionality to edit the products.
=> Add product edit functionality

components/dashboard/Logo.tsx, components/dashboard/SideBar.tsx
Fixes:
- Fixed the sidebar showing minimized and maximized dimensions in a wrong way.
- Fixed the sidebar not having any animation.
- Fixed the sidebar not having a full screen height.
=> Fix sidebar dimensions, animation & not extending to the screen height

app/dashboard/products/edit/[id]/page.tsx, app/dashboard/products/page.tsx, components/dashboard/SideBar.tsx, components/products/ProductActionsBar.tsx, components/products/ProductCreationForm.tsx, components/products/ProductEditForm.tsx, components/users/UserCreationForm.tsx, lib/actions/admin/products/deleteProduct.ts, lib/actions/admin/products/editProduct.ts, lib/actions/admin/users/createUser.ts, lib/utils/apiResponseValidator.ts, lib/utils/fetchImages.ts
Add
- product delete functionality
=> Add product delete functionality

app/dashboard/profile/page.tsx
Fixes:
- Fixed the Profile component throwing type mismatch warning on profile page by providing conditional rendering.
=> Add conditional rendering to fix type error on profile page

app/dashboard/company/create/page.tsx, components/company/CompanyCreationForm.tsx, components/company/CompanyDocument.tsx, lib/actions/company/createCompany.ts, lib/schema/schema.ts, types/schema-types.ts
Added:
- Functionality to create companies.
=> Implement company creation functionality

app/dashboard/company/page.tsx, app/dashboard/profile/page.tsx, components/company/CompanyCard.tsx, components/profile/Profile.tsx, types/types.d.ts
Add
- get user company functionality
=> Add get user company functionality

app/layout.tsx, components/UI/ConfirmationModal.tsx, components/products/ProductActionsBar.tsx, components/profile/Profile.tsx, package-lock.json, package.json, tailwind.config.ts
Add
- confirmation modal component.
- Ark ui library to create portal for modal.
- framer motion for animations on open and close actions.
=> Add confirmation modal using ark ui

app/dashboard/products/[id]/page.tsx, components/products/ProductDetails.tsx
Add
- create product details page
- fetch single product from API
=> Add product details page

components/auth/login/LoginForm.tsx, components/products/ProductActionsBar.tsx, components/products/ProductCreationForm.tsx, components/products/ProductDetails.tsx, components/products/ProductEditForm.tsx, components/users/UserCreationForm.tsx, lib/utils/apiResponseValidator.ts
Added:
- Implemented a feature to either use generic error messages or custom error messages for different status codes.
=> Implement custom error message feature for API response validator

components/UI/ErrorMessage.tsx, components/products/ImageUpload.tsx, components/products/ProductEditForm.tsx
Fix
- Implemented image size validation
=> Fix uploaded image size validation bug

app/auth/emailConfirmation/page.tsx, lib/actions/auth/auth.ts
Add
- email confirmation page success notification
=> Add notification for email confirmation

app/dashboard/orders/page.tsx, app/dashboard/products/[id]/create-order/page.tsx, app/dashboard/products/[id]/page.tsx, app/dashboard/profile/page.tsx, components/UI/Button.tsx, components/UI/DatePickerComp.tsx, components/dashboard/Navigation.tsx, components/orders/OrderCreationForm.tsx, components/products/ProductDetails.tsx, components/profile/Profile.tsx, lib/actions/orders/CreateOrder.ts, lib/schema/schema.ts, package-lock.json, package.json, types/schema-types.ts, types/types.d.ts
Add
- create order page
- create order functionality
- create order validation
- enhanced error handling by improving the reception and processing of error information.
=> Add order product functionality

app/dashboard/company/create/page.tsx, app/dashboard/users/create/page.tsx, components/company/CompanyCreationForm.tsx, components/orders/SingleCompanyOrderTypeSelector.tsx, components/orders/SingleCompanyOrdersTable.tsx, components/users/UserCreationForm.tsx, lib/constants/constants.ts
Refactor 
- rename confirmed into approved and use PageLayoutComp for wrapping
=> Refactor rename confirmed into approved and use Page Layout Component

components/UI/DatePickerComp.tsx, components/orders/OrderCreationForm.tsx, lib/schema/schema.ts, types/schema-types.ts
Fix date picker error handling issue
- displaying error messages correctly in other cases.
=> Fix date picker error handling issue

app/dashboard/products/page.tsx, app/dashboard/profile/page.tsx, components/products/ProductsWrapper.tsx, components/profile/Profile.tsx
Fixes:
- Make sure to not show the buttons that are not meant for certain type of users.
=> Remove the button visibility for unauthorized users
